### ISSUE TITLE
Announcement checklist 🎉

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/zodiac#21]
Things we need to get done before announcing Zodiac

- [ ] Complete audit of all Zodiac and module contracts. @auryn-macmillan

- [ ] Tag a github release of Zodiac. @auryn-macmillan 
  - [ ] Publish new version of Zodiac to NPM @cbrzn 

- [ ] Tag a new release of each of the modules @auryn-macmillan 
  - [ ] Add singleton library to each module @cbrzn / @carlosfebres 
  - [ ] Update yarn.lock in modules. @auryn-macmillan 
  - [ ] Deploy master copies via the singleton factory. @auryn-macmillan 
  - [ ] Also deploy the module factory via the singleton factory. @auryn-macmillan 
  - [ ] Update master copy addresses in Zodiac repo

- [ ] Deploy and publish the Safe app. @carlosfebres 
  - [ ] Update master copy addresses in Safe App @carlosfebres 
  - [ ] Also in any zodiac or module documentation @carlosfebres / @cbrzn 
  - [ ] Update [oracle address](https://github.com/RealityETH/monorepo/commit/56d97fdb1584d29c475648fcda1799bdd6c2f25a) to Reality V3 in documentation and safe app. @cbrzn 
  - [ ] finalize any design / front end changes (including new logos) @samepant / @carlosfebres 

- [ ] Make sure SafeSnap supports the new version of the Reality module and RealityV3 contracts. @carlosfebres 

- [ ] Make sure all documentation is up-to-date. @keikreutler 

- [ ] Relax and enjoy the launch 🍻
